server:
  port : 8080
spring:
  application:
    name: "AluraFlix"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aluraflix-db.csjg1fmwjtxz.us-west-1.rds.amazonaws.com:3306/alch
    username: root
    password: root1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true